name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up k3d
      run: |

        k3d --version

    - name: Create k3d cluster
      run: |
        # Create k3d cluster
        k3d cluster create my-cluster

        # Write kubeconfig to the default location
        k3d kubeconfig write my-cluster

        # Debug: Check kubeconfig file content
        cat $HOME/.kube/config
        kubectl config view

    - name: Install kubectl
      run: sudo apt-get install -y kubectl

    - name: Run kubectl commands
      run: |
        kubectl get nodes
