name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        kubectl config set-cluster my-cluster --server=${{ secrets.KUBE_API_SERVER_URL }}

    - name: Install kubectl
      run: sudo apt-get install -y kubectl

    - name: Run kubectl commands
      run: |
        kubectl get nodes
        kubectl apply -f k8s/deployment.yaml
